name: PR trigger
on: [pull_request]
jobs:
  run-ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository to runtime environment
        uses: actions/checkout@v3
      - name: Tear up infrastructure
        run: make up
      - name: Test db
        run: docker exec db pg_isready
      - name: CI
        run: make ci